"""Initial migration.

Revision ID: 5f37cff96800
Revises: 
Create Date: 2022-09-03 14:50:31.932930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f37cff96800'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parentId', sa.Integer(), nullable=False),
    sa.Column('mask', sa.LargeBinary(), nullable=False),
    sa.Column('polygon', sa.Text(), nullable=False),
    sa.Column('coords', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mask')
    # ### end Alembic commands ###
